"""Closed word lists used across the six authorship profiles.

Single source of truth: no list here may be duplicated into an extractor.
Changing a list changes what the engine measures, so any edit must bump
`EXTRACTOR_VERSION` in `ai/features/registry.py` - previously stored scores
stop being comparable otherwise.
"""

# The ~150 most frequent English function words. Function-word usage is the
# strongest known authorship signal: it is topic-independent and largely
# unconscious. This vector is the basis of the Stylistic profile.
FUNCTION_WORDS: tuple[str, ...] = (
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "almost",
    "along",
    "already",
    "also",
    "although",
    "always",
    "am",
    "among",
    "an",
    "and",
    "another",
    "any",
    "anything",
    "are",
    "around",
    "as",
    "at",
    "back",
    "be",
    "became",
    "because",
    "been",
    "before",
    "being",
    "below",
    "besides",
    "between",
    "both",
    "but",
    "by",
    "can",
    "cannot",
    "could",
    "did",
    "do",
    "does",
    "down",
    "during",
    "each",
    "either",
    "else",
    "enough",
    "even",
    "ever",
    "every",
    "few",
    "for",
    "from",
    "further",
    "had",
    "has",
    "have",
    "he",
    "hence",
    "her",
    "here",
    "hers",
    "him",
    "his",
    "how",
    "however",
    "i",
    "if",
    "in",
    "indeed",
    "instead",
    "into",
    "is",
    "it",
    "its",
    "itself",
    "just",
    "least",
    "less",
    "many",
    "may",
    "me",
    "might",
    "more",
    "most",
    "much",
    "must",
    "my",
    "neither",
    "never",
    "nevertheless",
    "no",
    "nor",
    "not",
    "nothing",
    "now",
    "of",
    "off",
    "often",
    "on",
    "once",
    "one",
    "only",
    "or",
    "other",
    "our",
    "out",
    "over",
    "perhaps",
    "quite",
    "rather",
    "really",
    "same",
    "she",
    "should",
    "since",
    "so",
    "some",
    "still",
    "such",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "though",
    "through",
    "thus",
    "to",
    "too",
    "under",
    "until",
    "up",
    "upon",
    "us",
    "very",
    "was",
    "we",
    "were",
    "what",
    "when",
    "where",
    "whether",
    "which",
    "while",
    "who",
    "whom",
    "whose",
    "why",
    "will",
    "with",
    "within",
    "without",
    "would",
    "yet",
    "you",
    "your",
)

# Discourse connectives, grouped so the *shape* of a writer's transition use
# can be compared, not just how often they transition.
TRANSITIONS: dict[str, tuple[str, ...]] = {
    "additive": (
        "also",
        "furthermore",
        "moreover",
        "in addition",
        "additionally",
        "besides",
        "as well as",
        "similarly",
        "likewise",
        "not only",
    ),
    "adversative": (
        "however",
        "nevertheless",
        "nonetheless",
        "on the other hand",
        "in contrast",
        "conversely",
        "although",
        "even though",
        "whereas",
        "despite",
        "in spite of",
        "yet",
        "still",
        "but",
    ),
    "causal": (
        "because",
        "since",
        "therefore",
        "thus",
        "hence",
        "consequently",
        "as a result",
        "accordingly",
        "due to",
        "owing to",
        "so that",
    ),
    "temporal": (
        "then",
        "next",
        "afterwards",
        "meanwhile",
        "subsequently",
        "finally",
        "eventually",
        "at first",
        "later",
        "before long",
        "simultaneously",
    ),
    "exemplifying": (
        "for example",
        "for instance",
        "such as",
        "namely",
        "in particular",
        "specifically",
        "to illustrate",
        "that is",
    ),
    "concluding": (
        "in conclusion",
        "to conclude",
        "in summary",
        "to sum up",
        "overall",
        "in short",
        "all in all",
        "ultimately",
    ),
}

# Pronouns by grammatical person. Person distribution is a stable stylistic
# habit (how much a writer foregrounds themselves, the reader, or others).
PRONOUNS: dict[str, tuple[str, ...]] = {
    "first_singular": ("i", "me", "my", "mine", "myself"),
    "first_plural": ("we", "us", "our", "ours", "ourselves"),
    "second": ("you", "your", "yours", "yourself", "yourselves"),
    "third_singular": (
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
    ),
    "third_plural": ("they", "them", "their", "theirs", "themselves"),
    "demonstrative": ("this", "that", "these", "those"),
}

# Contraction <-> expanded pairs. The *preference* between the two forms is
# more length-robust than a raw contraction rate.
EXPANDED_FORMS: tuple[str, ...] = (
    "do not",
    "does not",
    "did not",
    "is not",
    "are not",
    "was not",
    "were not",
    "has not",
    "have not",
    "had not",
    "will not",
    "would not",
    "could not",
    "should not",
    "cannot",
    "can not",
    "it is",
    "that is",
    "there is",
    "they are",
    "we are",
    "you are",
    "i am",
    "i will",
    "i have",
    "let us",
)

# "a" before these vowel-initial words is correct (consonant sound), and
# "an" before these consonant-initial words is correct (vowel sound).
A_BEFORE_VOWEL_OK: frozenset[str] = frozenset(
    {
        "university",
        "universe",
        "unique",
        "union",
        "unit",
        "united",
        "unicorn",
        "uniform",
        "useful",
        "user",
        "usual",
        "utility",
        "european",
        "euro",
        "eulogy",
        "ubiquitous",
        "one",
        "once",
        "ukulele",
        "usage",
        "utopia",
    }
)
AN_BEFORE_CONSONANT_OK: frozenset[str] = frozenset(
    {
        "hour",
        "honest",
        "honor",
        "honour",
        "heir",
        "heiress",
        "honorary",
        "honourable",
        "hourly",
    }
)

# Word pairs that are legitimately doubled, so the repeated-word rule
# doesn't fire on them.
LEGITIMATE_DOUBLES: frozenset[str] = frozenset(
    {"had had", "that that", "very very", "no no", "did did"}
)

# Contractions written without their apostrophe. High precision: these
# strings have essentially no other reading in English prose.
APOSTROPHE_OMISSIONS: tuple[str, ...] = (
    "dont",
    "cant",
    "wont",
    "isnt",
    "arent",
    "wasnt",
    "werent",
    "didnt",
    "doesnt",
    "hasnt",
    "havent",
    "hadnt",
    "couldnt",
    "shouldnt",
    "wouldnt",
    "im",
    "ive",
    "ill",
    "id",
    "youre",
    "youve",
    "youll",
    "theyre",
    "theyve",
    "thats",
    "whos",
    "lets",
    "wheres",
    "theres",
    "hes",
    "shes",
    "its",
)

# Homophone/idiom confusions detectable from a fixed context, not from
# meaning. Each entry is (regex, label).
HOMOPHONE_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"\btheir\s+(is|are|was|were)\b", "their/there"),
    (r"\byour\s+(going|coming|welcome)\b", "your/you're"),
    (r"\bits\s+(been|going\s+to)\b", "its/it's"),
    (r"\b(more|less|better|worse|rather|other)\s+then\b", "then/than"),
    (r"\b(could|should|would|must)\s+of\b", "of/have"),
    (r"\bloose\s+(the|a|his|her|their|my)\b", "loose/lose"),
    (r"\bto\s+(much|many)\b", "to/too"),
)

# Subject/verb pairs that disagree regardless of context. Both sides are
# closed-class, so precision is very high.
SV_DISAGREEMENTS: tuple[str, ...] = (
    r"\b(he|she|it)\s+(are|were|have|do)\b",
    r"\bi\s+(is|are|has|does)\b",
    r"\b(they|we|you)\s+(is|was|has|does)\b",
    r"\bthere\s+(is|was)\s+(many|several|few|two|three|four|five)\b",
)
